readers:
  - "urn:github:526301"
assets:
  config.yml: yegor256/home#assets/soalition/config.yml
  id_rsa: yegor256/home#assets/heroku-key
  id_rsa.pub: yegor256/home#assets/heroku-key.pub
install: |-
  export PATH=$PATH:/usr/lib/postgresql/10/bin
  sudo apt-get -y update
  sudo apt-get -y install libpq-dev
  sudo gem install pdd -v 0.20.5
  git config --global user.email "server@soalition.com"
  git config --global user.name "soalition.com"
release:
  sensitive:
    - config.yml
  script: |-
    pdd -f /dev/null
    export GEM_HOME=~/.ruby
    export GEM_PATH=$GEM_HOME:$GEM_PATH
    export LC_ALL=en_US.UTF-8
    bundle install --no-color
    ruby -v
    rake
    git remote add dokku dokku@www.soalition.com:soalition
    rm -rf ~/.ssh
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git fetch
    sed -i "s/0\.0\.0/${tag}/g" ./version.rb
    git add ./version.rb
    git commit -m 'build number set'
    cp ../config.yml config.yml
    rake config
    git add config.yml
    git commit -m 'config.yml'
    git push -f dokku $(git symbolic-ref --short HEAD):master
    git reset HEAD~1
    rm -rf target
    bundle exec rake liquibase
    rm -rf config.yml
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 http://www.soalition.com > /dev/null
  commanders:
  - yegor256
architect:
- yegor256
merge:
  commanders: []
  script: |-
    pdd -f /dev/null
    bundle install
    bundle exec rake
deploy: {}
